### ISSUE TITLE
ml_utils dependency is missing

### ISSUE THREAD

**Issue by yunshengtian** [a5a/asynchronous-BO#1]
Hi, thanks for the great repository. However, I cannot run the code without the ml_utils library, which is not currently present in this repository.

**Comment by yunshengtian** [comment]
Would you be able to provide the source code for ml_utils? This library does not seem to be a standard library that can be installed via PyPI and I was unable to find it anywhere else on the internet. The code just cannot run without this essential library. Thanks.

**Comment by rubinxin** [comment]
Hi Yunsheng,

Sorry for the late reply. Ahsan forgot to release the ml_utils folder. I've uploaded it to my repo which you can find it [here](https://github.com/rubinxin/asynchronous-BO). If this solves your problem, could you close the issue? Thanks

Best 
Robin

**Comment by yunshengtian** [comment]
Sure, thanks for the update!
